{% set version = "0.9.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggrepel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggrepel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggrepel/ggrepel_{{ version }}.tar.gz
  sha256: 29fb916d4799ba6503a5dd019717ffdf154d2aaae9ff1736f03e2be24af6bdfc

build:
  merge_build_host: true  # [win]
  number: 0
  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-scales                   # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - {{native}}toolchain        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base {{ r_version }}
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-rlang >=0.3.0
    - r-scales >=0.5.0
  run:
    - r-base {{ r_version }}
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-ggplot2 >=2.2.0
    - r-rlang >=0.3.0
    - r-scales >=0.5.0

test:
  commands:
    - $R -e "library('ggrepel')"           # [not win]
    - "\"%R%\" -e \"library('ggrepel')\""  # [win]

about:
  home: http://github.com/slowkow/ggrepel
  license: GPL-3.0-only
  summary: Provides text and label geoms for 'ggplot2' that help to avoid overlapping text labels. Labels repel away from each other and away from the data points.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-ggpubr"
    recipe-maintainers:
      - bkreider

